### ISSUE TITLE
Add a favicon to the website

### ISSUE THREAD

**Issue by kazzkiq** [christian-fei/pomodoro.cc#101]
Hey, first of all: Thanks for this project! Its beautiful and helps a lot with my productivity. :smile: 

So, I think that it would be interesting to add a favicon, so when you pin the browser tab it gets easier to identify Pomodoro.

Today it looks like that:
<img width="227" alt="captura de tela 2016-03-29 as 21 45 14" src="https://cloud.githubusercontent.com/assets/1953194/14128417/320cc2ac-f5f7-11e5-894c-552980ba80a3.png">
<img width="234" alt="captura de tela 2016-03-29 as 21 45 37" src="https://cloud.githubusercontent.com/assets/1953194/14128424/39a9f5b6-f5f7-11e5-8463-095e40ef297b.png">
<img width="229" alt="captura de tela 2016-03-29 as 21 46 03" src="https://cloud.githubusercontent.com/assets/1953194/14128427/3e0f1582-f5f7-11e5-92e2-ba70e935c458.png">

**(Chrome, Firefox and Safari, respectively)**

**Comment by christian-fei** [comment]
Good point!

Thank you very much :)

**Comment by christian-fei** [comment]
Done :)
