### ISSUE TITLE
Statistics aren't working for me

### ISSUE THREAD

**Issue by alexpelan** [christian-fei/pomodoro.cc#103]
Thanks for all your work on this tool - it's really useful.

The statistics page doesn't seem to be working for me - the todos show up properly, but it always says that I have completed 0 pomodoros. There's an error in the javascript console:

Here are a couple partial stack traces, and a screenshot of the empty graph (see NaN along the x-axis):
https://www.dropbox.com/s/vr7ga00rpcke8s3/Screen%20Shot%202016-04-23%20at%201.32.24%20PM.png?dl=0

https://www.dropbox.com/s/yqt1s4wevw2kcru/Screen%20Shot%202016-04-23%20at%201.32.13%20PM.png?dl=0

https://www.dropbox.com/s/tmqjhw21sghbc63/Screen%20Shot%202016-04-23%20at%201.31.59%20PM.png?dl=0

I'm on Chrome 49.0.2623.112, Max OS X 10.10.5

**Comment by christian-fei** [comment]
Thank you so much for the report!
I will work on it. If you find some time, a PR would mean a lot.
Your feedback is very appreciated, it's what keeps me going :)

**Comment by matsair** [comment]
I have the same problem. Statistics aren't showing.
Running Chrome 50 and Mac OS X 10.11.4

https://dl.dropboxusercontent.com/u/44511321/screen1.png
https://dl.dropboxusercontent.com/u/44511321/screen2.png

**Comment by christian-fei** [comment]
Thanks  @alexpelan , @matsair for reporting.

I found some time today, and it's finally fixed :)
