### ISSUE TITLE
Statistics aren't saved

### ISSUE THREAD

**Issue by matsair** [christian-fei/pomodoro.cc#104]
I did x pomodoros yesterday, but today the statistics page says "Not enough data..."
Are only pomodoros of the current day shown?
Feature or bug?

**Comment by christian-fei** [comment]
Hey @matsair ,
yeah. currently the statistics are for the current day only.
When I find some time this week I will add this feature!

Thanks for your interest :)

**Comment by christian-fei** [comment]
You can take a look at yesterday's pomodoros with the following url:

https://pomodoro.cc/api/pomodoros?day=2016/05/09

If you have paginated results (see the headers `x-page` and `x-pages`) you can navigate through the results with

https://pomodoro.cc/api/pomodoros?day=2016/05/09&page=2
https://pomodoro.cc/api/pomodoros?day=2016/05/09&page=3
etc.

**Comment by christian-fei** [comment]
Now I have a very basic implementation working,
cheers, and expect changes for this feature :)

e.g. https://pomodoro.cc/statistics?day=2016/05/10
