### ISSUE TITLE
keyboard shortcuts and possibly automatic start of breaks/ work

### ISSUE THREAD

**Issue by henningsway** [christian-fei/pomodoro.cc#106]
would be appreciated. :D

**Comment by christian-fei** [comment]
hey @henningsway!
thanks for the interest! This could be indeed pretty useful.
I'm swamped right now, if I find some time, I will try to implement it.
If you manage to understand the frontend code, a PR is more than appreciated though :)

**Comment by christian-fei** [comment]
Just letting you know that i am working on http://beta.pomodoro.cc

Closing this for now :)
