### ISSUE TITLE
Icons for disabling sounds not visible in Firefox

### ISSUE THREAD

**Issue by BorislavZlatanov** [christian-fei/pomodoro.cc#108]
I hear the ticking sound the entire time and it is distracting me from the work. I would like to be able to hear only the alarm when the timer reaches 0.

Great app, by the way. Thank you for the work!

**Comment by BorislavZlatanov** [comment]
OK, my bad, I see there is an option to turn off both the ticking sound and the alarm. But somehow those two icons don't show to me in Firefox. Here's a screenshot:

![firefox](https://user-images.githubusercontent.com/3427319/27681446-efcb9628-5cc7-11e7-8afd-8901161866be.jpg)

And with a mouse hover:

![firefox_hover](https://user-images.githubusercontent.com/3427319/27681458-fb1dacdc-5cc7-11e7-8bfd-fe140014d524.jpg)

I looked at the CSS but couldn't figure out why the icons don't show in Firefox.

**Comment by christian-fei** [comment]
Just letting you know that i am working on http://beta.pomodoro.cc

Closing this for now :)
