### ISSUE TITLE
Keep statistics history 

### ISSUE THREAD

**Issue by BorislavZlatanov** [christian-fei/pomodoro.cc#109]
I find the Statistics functionality really powerful and it was one of the main features that made me switch to pomodoro.cc from the other Pomodoro timer I was using.

What would be very useful to me is to keep a history of the daily statistics. So, below the Victory chart, there could be a table with the last 30 days (or so). The table would look something like:

| Date | Pomodoros | Hours |
| ----- | ----------- | -------- |
| January 2nd | 5 | 2 |
| January 1st | 8 | 3.3 |

And so on. 

What do you think?

**Comment by christian-fei** [comment]
hello, thank you so much for the interest! i will look into it once i get a pc in the next weeks :)

**Comment by christian-fei** [comment]
Just letting you know that i am working on http://beta.pomodoro.cc

Closing this for now :)
