### ISSUE TITLE
Add option to change alarm sound

### ISSUE THREAD

**Issue by BorislavZlatanov** [christian-fei/pomodoro.cc#110]
I find myself jumping up on the chair a little bit when the alarm sound rings. It would be really nice to have the ability to choose other alarm sounds. This way people can choose whatever they prefer.

My personal preference would be for a short and undisturbing sound. Like the "Elevator bell" sound [here](https://www.zapsplat.com/sound-effect-category/elevator/).

**Comment by christian-fei** [comment]
Just letting you know that i am working on http://beta.pomodoro.cc

Closing this for now :)

**Comment by BorislavZlatanov** [comment]
@christian-fei Awesome, looking forward to seeing the new version.
