### ISSUE TITLE
webpack emit css

### ISSUE THREAD

**Issue by christian-fei** [christian-fei/pomodoro.cc#126]
is it possible to emit a separate .css file?

probably it's better to go with stylus and compile the css directly..

**Comment by juanarbol** [comment]
I'll try this one

**Comment by christian-fei** [comment]
That would be awesome! Thanks

**Comment by juanarbol** [comment]
That's it! [#127](https://github.com/christian-fei/pomodoro.cc/pull/127)

**Comment by christian-fei** [comment]
Thank you @juanarbol !
