### ISSUE TITLE
Browser(s) add-on for time tracking

### ISSUE THREAD

**Issue by juanarbol** [christian-fei/pomodoro.cc#129]
Most popular time trackers use add-on for your favorite browser, so you do not have to change tab for stopping your timer (for any important o regular reason), this creates a very nice experience with the product.

**Comment by christian-fei** [comment]
this is a nice idea! i had a repo some time ago with a prove-of-concept working, but it's now long gone sadly.. 😅
i would like to discuss with you the possibility to develop an extension for pomodoro.cc, that would be awesome, really :)

**Comment by juanarbol** [comment]
I haven't developed one before, to be honest I have no idea about how to do it; but learn how to would be a big challenge I want to take it.

Ooh, and what do you think about it works with trello too?

**Comment by christian-fei** [comment]
hmm i don't want to include too many things, this should remain a simple time tracking and todo list project. :)

**Comment by juanarbol** [comment]
for sure? Trello is a very nice tool for agile

**Comment by christian-fei** [comment]
hmm, it would be nice to see it though! if you like, you could make a pr, that would be cool

**Comment by juanarbol** [comment]
Ok, I'll try it!

**Comment by juanarbol** [comment]
I've read Trello API docs'; yo do not need to create any browser extension, you create apps for Trello. I'm gonna close this issue and work on Trello app for the next PR!

**Comment by juanarbol** [comment]
Sorry dude, I've been busy; but I've been working on it!

**Comment by christian-fei** [comment]
Woohoooo 🚀 can't wait! 💯
