### ISSUE TITLE
Webhook to push promodoro data 

### ISSUE THREAD

**Issue by thejeshgn** [christian-fei/pomodoro.cc#175]
It will be great if you can push the data to a webhook. It can be used to trigger other stuff.

**Comment by christian-fei** [comment]
Hello @thejeshgn 

Thanks for the feedback! If I understood correctly, we could achieve this through an API.
It is planned in the coming months


PS: we now have a Patreon if you want to support the development  https://www.patreon.com/pomodoro_cc

**Comment by christian-fei** [comment]
@thejeshgn with the latest release in Pomodoro.cc Pro, your activity gets saved in the cloud and you'll be able to retrieve it through an API!

Check it out here https://pomodoro.cc/pro
