### ISSUE TITLE
pomodoro.cc/public

### ISSUE THREAD

**Issue by cedewey** [christian-fei/pomodoro.cc#177]
I saw in [this comment](https://www.producthunt.com/posts/pomodoro-cc#comment-101617 ) that you had created a pair programming view at pomodoro.cc/public. My company is very interested in having the ability to share and see one another's pomodoros. 

Do you have any intention of bringing this back? We might even be able to support the work with some modest donations.

Thanks!

**Comment by christian-fei** [comment]
Hello @cedewey!

Many thanks for the interest! 

I definitely want to work on this feature, and I think it's feasible in a reasonable amount of spare time spent on it.

I added a new goal to the [Patreon page](https://www.patreon.com/pomodoro_cc) to get people interested and also be funded through the interest of the community :)

Here you can find the official Patreon page:

https://www.patreon.com/pomodoro_cc

**Comment by christian-fei** [comment]
@cedewey let me know what you think and if it suits your needs

http://pomodoro.cc/pair/cedewey

![pair-2](https://user-images.githubusercontent.com/2662706/57814632-99196200-7774-11e9-9877-cbf2393856a9.gif)

**Comment by christian-fei** [comment]
@cedewey any news?

**Comment by cedewey** [comment]
Hi Christian, thanks so much for bringing this feature back! I appreciate the time you spent on it. As an initial, lightweight solution to sync up with one other person it's working well. 

We have an eye towards something that can give each of us a look at what the other is up to and how they're doing, very similar to what https://tomato5.io/ was trying to accomplish. That tool proved to be too buggy and limited for our purposes though.

I'm not sure whether that would fall into the scope of your project, but is what we're wanting to move towards eventually.

For the purposes of this original issue I consider it fixed and will let my friends and colleagues know it's available. Thanks!
