### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by szoper** [christian-fei/pomodoro.cc#178]
Hi
Great tool! I've been using it for a couple of weeks, but since a week or so, the sound stopped working.  
The only error I can see in developer tools is a `401` from `https://api.pomodoro.cc/info`, but I'm not sure if it is related.

```
curl 'https://api.pomodoro.cc/info' -H 'Referer: https://pomodoro.cc/' -H 'Origin: https://pomodoro.cc' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36' -H 'DNT: 1' --compressed
```

Could you fix it?

**Comment by christian-fei** [comment]
Hey @szoper !
Thank you for the feedback, it is a known issue, want to bring it back in the next weeks

PS: This isn't related to the `401` error you're seeing, it's only because you're not logged in :)

**Comment by christian-fei** [comment]
@szoper the sounds are back for logged in users!
