### ISSUE TITLE
A long TODO text covers the cross

### ISSUE THREAD

**Issue by ilbonte** [christian-fei/pomodoro.cc#179]
In the image below I've highlighted the "destroy button"

![image](https://user-images.githubusercontent.com/7412876/58161110-f6834680-7c7f-11e9-8119-717a2cfc1cdd.png)

**Comment by christian-fei** [comment]
Hey @ilbonte ,
thank you the feedback,
I am thinking about an improved implementation also with an UX designer to improve the experience

**Comment by christian-fei** [comment]
Should be fixed once this build passes and deploys

https://circleci.com/gh/christian-fei/pomodoro.cc/1148

**Comment by christian-fei** [comment]
@ilbonte do you approve the changes?
