### ISSUE TITLE
Unable to play sound in Firefox 39.0

### ISSUE THREAD

**Issue by joebew42** [christian-fei/pomodoro.cc#18]
I'm using pomodoro.cc with Firefox 39.0. Unfortunately I can't hear the ticking sound.

**Comment by christian-fei** [comment]
Strange, I tested on all major browsers (on OSX) and it works well.
Could you kindly give me some more information about the logs in the console, maybe there is an error?

Will introduce https://errorception.com/ in the next release, to catch this bugs earlier.

Thank you

**Comment by joebew42** [comment]
This is the output of the browser console:

```
Specified "type" attribute of "audio/mpeg" is not supported. Load of media resource /assets/audio/ring.mp3 failed. pomodoro.cc
All candidate resources failed to load. Media load paused. pomodoro.cc
Specified "type" attribute of "audio/mpeg" is not supported. Load of media resource /assets/audio/tick.mp3 failed. pomodoro.cc
All candidate resources failed to load. Media load paused. pomodoro.cc
```

**Comment by christian-fei** [comment]
Aaaah, that's interesting. Thanks

**Comment by christian-fei** [comment]
Should be fixed with 60b1e2c5a335a15cd398bf577a880810165191c3

Build: https://circleci.com/gh/christian-fei/pomodoro.cc/572

**Comment by joebew42** [comment]
I've just tested and it works well! Thank you!

**Comment by christian-fei** [comment]
That's f#+*.- awesome, thanks for testing it!
