### ISSUE TITLE
Pinned tab unable to see countdown

### ISSUE THREAD

**Issue by thisislawatts** [christian-fei/pomodoro.cc#180]
When using this web tool within a pinned tab the title is not displayed. By introducing an animated favicon the products usability is improved.

See attached for an example of how it could work (sped up to fit within gif):  

![Kapture 2019-09-30 at 22 28 50](https://user-images.githubusercontent.com/472589/65914653-1109c100-e3d2-11e9-8d20-120d359119ed.gif)

**Comment by christian-fei** [comment]
@thisislawatts hello ! that's a cool idea, i have to look into how to get this to work.
maybe you can work on it @thisislawatts ?
