### ISSUE TITLE
Running this post shutdown

### ISSUE THREAD

**Issue by theg00s3** [christian-fei/pomodoro.cc#184]
I know that you shut this site down because of copyright concerns, but is there a way to selfhost this with the logged in user features?

**Comment by christian-fei** [comment]
Hello @theg00s3 !

Thanks for the interest, I have to look into it. I just kindly ask you, if you self-host it on the web, to remove my name.

Will let you know when I come up with something. Maybe a video call is more constructive.

Let me know if it's ok

**Comment by christian-fei** [comment]
reference: https://github.com/theg00s3/pomodoro.cc/commit/da309293166558a74c18351f34d5070c237ecd2b
