### ISSUE TITLE
Improve gps coordinates exctraction

### ISSUE THREAD

**Issue by pdincau** [christian-fei/pomodoro.cc#21]
what do you think about changing https://github.com/christian-fei/pomodoro.cc/blob/master/ws/web/transports/web_socket_ip.ex#L71-L72 like this?

    defp conn_ip(conn) do
     {"x-real-ip", ip} = List.keyfind(conn.req_headers, "x-real-ip", 0)
    end

btw this makes me thinks that probably this could be generalized so that you can extract whatever header you want and probably we should pass the headers and not all the conn.

**Comment by christian-fei** [comment]
Thanks for the insight, introduced your suggestions with 3a1fe7844f800071e074b0ec97133d690c3e8f50
