### ISSUE TITLE
Extract gps coordinates using a function

### ISSUE THREAD

**Issue by pdincau** [christian-fei/pomodoro.cc#22]
what about rewriting https://github.com/christian-fei/pomodoro.cc/blob/master/ws/web/transports/web_socket_ip.ex#L71-L72 as:

    {latitude, longitude} = gps_coordinates_from(body)

btw I think that all the stuff related to gps should go in a separate module that implements the calls to the external service, so that you could have:

    {latitude, longitude} = Freegeoip.coordinates_for(ip)

**Comment by christian-fei** [comment]
Thanks for the insight, introduced your suggestions with 3a1fe7844f800071e074b0ec97133d690c3e8f50
