### ISSUE TITLE
Add check list for activities

### ISSUE THREAD

**Issue by christian-fei** [christian-fei/pomodoro.cc#28]
```
As a user
I want to have a check list of things I have to do
So that I can keep track of my progress
```

Discussion:
The checklist should be persisted. Checklist items can be created, marked as done, modified and deleted. 

I think that an (always visible) checklist on the dashboard would be overwhelming for the user.
We could either make a dedicated page (it could make sense)
or
a button that shows/hides the checklist.

**Comment by pdincau** [comment]
what about doing this with elixir and plug?

**Comment by christian-fei** [comment]
Yeah I think this could be the first step to move to a fresh, new and maintainable api
The idea could be this:

Since the current api-service is 1) the api itself and 2) the authorizer, we could let the authorizer do its thing and separate the two responsabilities.

There is one catch though: the current persistence mechanism is mongodb, and although I don't necessarily hate it, I would like try and to move to a new one (pgsql). So Ecto with its pgsql adapter could come in handy, and we should have everything in place :)

## The plan

I will try to visualize what I have in mind:

```
                           |-----------------------------------|
                           |                client                 |
                           |-----------------------------------|
                                      |
                                      | makes request (e.g. create new task)
                                      >
                           |-----------------------------------|
                           |             api + auth             |
                           |-----------------------------------|
                                    |
                                    | proxies request for /api/tasks (e.g.) to:
                                    >
                           |-----------------------------------|
                           |        new api in elixir         |
                           |-----------------------------------|
```

From here we can move to port the api to elixir

**Comment by pdincau** [comment]
@christian-fei ok for postgres. So the idea is to store only the activities in postgres?

**Comment by christian-fei** [comment]
@pdincau yes exactly, for now the two api don't know that they even exist

But elixir will take over
