### ISSUE TITLE
Would be cool to ave some sort of daily competition

### ISSUE THREAD

**Issue by jnardiello** [christian-fei/pomodoro.cc#39]
It would be cool to have some sort of "gamefication" with a daily competition across users on who is making more pomodoros (and less interruptions).

**Comment by christian-fei** [comment]
Hey!
Interesting.. I find it a really great idea to "gameify" the experience, not sure if against/with other users or challenge yourself to get better (less interruptions as you said, etc.)

You could earn "points" by
- being less interrupted
- checking more tasks from the todo list
- ...

:+1: :)

I will think about it and continue the discussion here when I'm working on it.

If you have time and want to help you could fork and propose a change :)

PS: keep an eye on the `app_v2` folder where the party is going on now

**Comment by christian-fei** [comment]
Hello, I thought about this more.
A competition against other is not really the point of the technique.
What *is* interesting is your idea applied to the statistics of the user, but without the gamification factor :)
