### ISSUE TITLE
Menu is not working on Firefox

### ISSUE THREAD

**Issue by cstipkovic** [christian-fei/pomodoro.cc#4]
Hey @christian-fei  :)

First, tks for the pomodoro.cc ;)

So, I'm trying to use it on Firefox 38, but when try to click on "Dashboard" and happens a focus out of the menu, it closes and I can't login, for example.

tks :)

**Comment by christian-fei** [comment]
Oops, thank you very much for using pomodoro.cc and for reporting this
issue!

PS: feel free to make suggestions and feature requests, I would really
appreciate it :)

**Comment by christian-fei** [comment]
@cstipkovic should be fixed with this build :)
Thanks again.

https://circleci.com/gh/christian-fei/pomodoro.cc/96

**Comment by cstipkovic** [comment]
@christian-fei tks :)

I was testing the fix and menu is appearing on Firefox now, but I can't click on the items, maybe some z-index between menu and the content.

Best.
