### ISSUE TITLE
Add projects to sum up pomodoros into

### ISSUE THREAD

**Issue by evictorov** [christian-fei/pomodoro.cc#40]
I love your design but feel it lacks a nice feature - sup up pomodoros into projects.

I've been using the www.tomato.es service before and as a user I can add tags for each pomodoro, afterwards I can create a project and assign tags for it - so pomodoros with those tags will count up for this project.

Personally, I'd be happy if you could just merge two services :pray: because both of them are great each in some way.

:v:

**Comment by christian-fei** [comment]
Hey, thanks!
This would be indeed awesome and is already a work in progress :)

It will be released soon, keep an eye on https://pomodoro.cc/beta to get the nightly development updates!
In the next days it will be implemented as you suggested.

Really appreciate your suggestion.

Please tell me how you like the new design of https://pomodoro.cc/beta .
I can adapt it to your ideas

**Comment by christian-fei** [comment]
Hello!

Referenced your issue here: https://github.com/christian-fei/pomodoro.cc/issues/56

Closing for now, the development will continue in #56
