### ISSUE TITLE
checkbox on firefox looks ugly

### ISSUE THREAD

**Issue by fain182** [christian-fei/pomodoro.cc#43]
The checkbox is way too large on firefox 42 on mac.

<img width="335" alt="screen shot 2015-12-07 at 19 33 38" src="https://cloud.githubusercontent.com/assets/5879/11635913/b29c27b4-9d19-11e5-973f-a14100a367e6.png">

**Comment by christian-fei** [comment]
Thanks for reporting!

**Comment by christian-fei** [comment]
Fixed with https://github.com/christian-fei/pomodoro.cc/commit/c9536a8c4b41fbd13e42f5dcaaa61f3eac3faef8

Once [249](https://travis-ci.org/christian-fei/pomodoro.cc/builds/95442362) passes, this is online

Thanks!

**Comment by christian-fei** [comment]
Should be up! Please tell me what you think so that I can eventually close this issue :)

**Comment by fain182** [comment]
now it's much better! :+1:
