### ISSUE TITLE
There are no links "support" or "report feedback/bug" in the website

### ISSUE THREAD

**Issue by fain182** [christian-fei/pomodoro.cc#44]
I can't find a link to ask for support or report a bug.

**Comment by christian-fei** [comment]
Good point, didn't think about it!

**Comment by christian-fei** [comment]
This should work, what do you think?
https://github.com/christian-fei/pomodoro.cc/commit/3618377b951a1343e7580d31b5631b057150274d

**Comment by fain182** [comment]
This problem is solved, maybe the footer is becoming a little bit too tall and crowded, but design is not my area of expertise ;-)

**Comment by christian-fei** [comment]
Thanks, I will think about this
