### ISSUE TITLE
Ticking sound stops if I focus another tab

### ISSUE THREAD

**Issue by kaldrenon** [christian-fei/pomodoro.cc#5]
In Chrome, if I start a pomodoro and then select another tab in the same window, the ticking sound ends (but the timer still counts down). If I cycle back to the tab, the ticking resumes.

**Comment by kaldrenon** [comment]
After some more investigation, the ticking sound also stops if:

* I have the tab in its own window, but cover that window completely with another Chrome window
* I have the tab in its own OSX workspace and then switch back to another workspace.

Basically, it seems like it stops as soon as the timer is no longer visible.

**Comment by christian-fei** [comment]
Thanks, will look into this.
:+1:

**Comment by christian-fei** [comment]
It is fixed with the newer version
let me know if the issue if fixed for you!

**Comment by kaldrenon** [comment]
Working for me. Thanks!

**Comment by christian-fei** [comment]
nice :)
