### ISSUE TITLE
Unable to mute sounds on safari

### ISSUE THREAD

**Issue by christian-fei** [christian-fei/pomodoro.cc#57]
https://twitter.com/jikkujose/status/682424653030113280

code: https://github.com/christian-fei/pomodoro.cc/blob/master/app/src/modules/Sounds.js

**Comment by somerandomteen** [comment]
It's a bug within the sound library you're using it seems, not your code. https://github.com/jaysalvat/buzz/issues/80

**Comment by christian-fei** [comment]
@somerandomteen well, thank you very much! didn't think about that honestly..

Will see if I can fix it upstream, else I will use another lib.

**Comment by christian-fei** [comment]
set `webAudioApi ` to false

as suggested in

https://github.com/jaysalvat/buzz/issues/80#issuecomment-168850480

**Comment by christian-fei** [comment]
Fixed
