### ISSUE TITLE
Introduce ramda.js

### ISSUE THREAD

**Issue by christian-fei** [christian-fei/pomodoro.cc#58]
http://ramdajs.com/0.19.0/index.html

**Comment by jdalton** [comment]
Where? On the website?

**Comment by christian-fei** [comment]
Hello, yes, on https://github.com/christian-fei/pomodoro.cc/tree/master/app :)

**Comment by jdalton** [comment]
Ah cool. You may dig that in 2 weeks lodash v4 will be released which will have a way to use immutable iteratee-first data-last auto-curried methods. It aligns closer to Underscore so refactoring won't have to be as dramatic.

**Comment by christian-fei** [comment]
Thanks for the tip! I dig lodash, wanted to experiment with ramda :)
Will keep this in mind, though, ramda seems a bit harsh for the first experiment

**Comment by jdalton** [comment]
The idea with lodash v4 is you can opt-in to ramda like behavior with something like
```js
var _ = require('lodash/fp');
_.map(doubled)(array);
```

**Comment by christian-fei** [comment]
yep exactly this is the main reason why i like it, especially the concept of composition that ramda enables and favors
