### ISSUE TITLE
Handle todaysPomodori state with redux

### ISSUE THREAD

**Issue by christian-fei** [christian-fei/pomodoro.cc#59]
currently some components/routes handle this state separately, although it's common across the application and is a central piece.

see 
- https://github.com/christian-fei/pomodoro.cc/blob/master/app/src/components/DailyPulse.js
- https://github.com/christian-fei/pomodoro.cc/blob/master/app/src/components/StatisticsStrip.js
- https://github.com/christian-fei/pomodoro.cc/blob/master/app/src/routes/Statistics.js

**Comment by CrocoDillon** [comment]
Why is this closed?

**Comment by christian-fei** [comment]
@CrocoDillon resolved with

https://github.com/christian-fei/pomodoro.cc/commit/547d092d4155627678d79956e2be8def78e6b3a6
https://github.com/christian-fei/pomodoro.cc/commit/2b0dca7b316ff89e27df49e41a2072d8e00246d1

but feedback is very welcome! :)

**Comment by CrocoDillon** [comment]
Awesome! Thought you changed your mind :p I can look at it after work, if I have any feedback I will let you know!

**Comment by christian-fei** [comment]
it would be awesome to get your feedback and do a small review, thank you!
