### ISSUE TITLE
Rate-limit api calls

### ISSUE THREAD

**Issue by christian-fei** [christian-fei/pomodoro.cc#62]
Probably this is a premature optimization. But it's good to keep this in mind, so let's talk.

---

We need to rate-limit the api-calls to make space for the developer program.

Users will be able to get a `client_id` and `client_secret` to access the api as a registered application.

So maybe we can think about rate-limiting the access to this `client_id` to "x requests/hour"

We could use [redis rate-limit pattern 1](http://redis.io/commands/incr#pattern-rate-limiter-1)

Also, take a look at these docs:

- https://developer.github.com/v3/rate_limit/
- http://blog.codinghorror.com/rate-limiting-and-velocity-checking/

**Comment by christian-fei** [comment]
As suggested [on twitter](https://twitter.com/wstucco/status/685056385567068161), we delegate this to [`ex_rated`](https://github.com/grempe/ex_rated)

**Comment by christian-fei** [comment]
At a first look, it doesn't have adapters for other storages except ETS.
This would not be ideal because at each deploy we restart the service. Maybe ETS can be persisted?

**Comment by christian-fei** [comment]
@pdincau do you have any suggestions about this?

**Comment by pdincau** [comment]
yes, ets tables is lost as soon as the owner process terminates.

**Comment by pdincau** [comment]
@christian-fei where is the reference to adapters?

**Comment by christian-fei** [comment]
@pdincau Ah I looked at the source and found out that it's hard-coded :disappointed:
E.g. [here](https://github.com/grempe/ex_rated/blob/master/lib/ex_rated.ex#L112) so I assume it works only with ETS.

**Comment by wstucco** [comment]
@christian-fei ETS cannot be persisted but [DETS](http://erlang.org/doc/man/dets.html) can :)

**Comment by christian-fei** [comment]
cleaning up issues, postponing this for later
