### ISSUE TITLE
As a user I want to undo a todo action so that I have a better experience.

### ISSUE THREAD

**Issue by christian-fei** [christian-fei/pomodoro.cc#63]
This introduces the functionality of "undo"-ing this operation.

We can use [`<Snackbar>`](http://www.material-ui.com/#/components/snackbar) to make this nice and working out of the box.

For the implementation of the undo-functionality see:
- http://rackt.org/redux/docs/recipes/ImplementingUndoHistory.html
- https://github.com/omnidan/redux-undo

**Comment by christian-fei** [comment]
working on it on https://github.com/christian-fei/pomodoro.cc/tree/63/undo_todo

**Comment by christian-fei** [comment]
I thought about it more, and it doesn't make much sense to make a todo disappear once completed.
you have to explicitly "erase it"/delete to get it off the list, like in a real todo-list.

Does this make sense?

**Comment by christian-fei** [comment]
Does this make sense for you?

![http://d.pr/i/6ms6](http://d.pr/i/6ms6)

**Comment by CrocoDillon** [comment]
Makes sense, it's rewarding to still see all the todos you have completed.

**Comment by christian-fei** [comment]
thanks!
