### ISSUE TITLE
No option to mute ticking sounds on new version

### ISSUE THREAD

**Issue by leoncvlt** [christian-fei/pomodoro.cc#7]
In the previous version we had options to mute ticking sounds and notification separately. I can't see the option on the new version, any way to disable that? Hate having the ticking sound on top of my music.

**Comment by christian-fei** [comment]
hey man, thanks for your interest :)
i'm currently without pc and wanted to add this feature (again), but thrn
my pc broke, so i'm out of luck.
it would be interesting to ser if you could implement something along these
lines, especially to see if the codebase is "friendly" enough.
let me know, else i'll add it once i get my pc back

**Comment by geekpete** [comment]
Yeah totally +1 on this. 

I need the alarm but I don't want the ticking.

**Comment by christian-fei** [comment]
got it back yesterday, will implement it in the next days :)

cheers

**Comment by geekpete** [comment]
Cool thanks!

Was currently using this one: http://www.pomodorotime.org/timer/

Will switch to pomodoro.cc once that ticking is fixed :)

**Comment by christian-fei** [comment]
Added this feature to the latest release, cheers :)
