### ISSUE TITLE
As a logged in user I want to participate to the beta program So that I can try out new features and give feedback about them

### ISSUE THREAD

**Issue by christian-fei** [christian-fei/pomodoro.cc#71]
We would like to launch a beta program that enables some features we would like to validate.

The user can subscribe/unsubscribe to the beta program through a dedicated page (like `/beta`).
The responsibility belongs definitely to the api-service, so it would be wrong to delegate it to `/auth/info`.. (just thinking out loud).

We need to track with mixpanel this property (via `identity`?).

There should also be a notice on the page (maybe on the header?) to inform the user that they are subscribed to the beta program.

The state will be handled by redux, maybe we can add it as a property to the `api` store.

# doubts

A note about the redux state and react rendering:

Probably it's best if the component "that is being tested" (e.g. is part of the beta program) doesn't know whether it should be rendered or not, but rather a container component (like `<BetaProgramEligible/>`) that has this responsibility.

What do you think?

**Comment by CrocoDillon** [comment]
I like the idea of the `<BetaProgramEligible/>` component. You can re-use this component easily everywhere your beta program (and future beta programs) inserts new components and when the beta is over you can just remove the `BetaProgramEligible` container if your users liked the feature.

**Comment by christian-fei** [comment]
:+1: , thanks :)

**Comment by fain182** [comment]
Maybe you could think to something like a feature flag..

```
<ShowIfToggled feature="something-new">
The UI of you feature...
</ShowIfToggled>
```

Anyway if you are thinking about "business" validation of your idea I am not sure that you need a beta testing group, your beta test users probably are a little bit different from your user base, a random user sample and little experiments would work better.

**Comment by christian-fei** [comment]
hmm, thanks. I will think about it!

**Comment by christian-fei** [comment]
cleaning up issues, postponing this
