### ISSUE TITLE
Ticking noise does not loop well

### ISSUE THREAD

**Issue by J3RN** [christian-fei/pomodoro.cc#93]
This is sort of petty, but the ticking noise has a very audible pause when looping, which sort of drives me crazy. Chrome 48.0.2564.109, OS X.

**Comment by christian-fei** [comment]
Thank you!
Will look into this to make it better

**Comment by christian-fei** [comment]
Just letting you know that i am working on http://beta.pomodoro.cc

Closing this for now :)
